[package]
name = "dota2-assistant"
version = "0.1.0"
edition = "2024"

[dependencies]
dota-gsi = { path = "../dota-gsi", features = ["models", "handlers", "diff"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net"] }
serde_json = "^1.0"
anyhow = "^1.0"
log = "^0.4"
env_logger = "^0.10"
clap = { version = "4.6", features = ["derive"] }
bytes = "1"
